import mongodb from "../../public/my_stack/mongodb.svg";
import express from "../../public/my_stack/express.svg";
import nodejs from "../../public/my_stack/nodejs.svg";
import prisma from "../../public/my_stack/prisma.svg";
import socket from "../../public/my_stack/socket.svg";
import nextjs from "../../public/my_stack/nextjs.svg";
import typescript from "../../public/my_stack/typescript.svg";
import javascript from "../../public/my_stack/javascript.svg";
import tailwind from "../../public/my_stack/tailwind.svg";
